# CMake generated Testfile for 
# Source directory: /Users/igorvasiljevic/opengv_devel/opengv
# Build directory: /Users/igorvasiljevic/opengv_devel/opengv/python
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_absolute_pose "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_absolute_pose")
set_tests_properties(test_absolute_pose PROPERTIES  WORKING_DIRECTORY "/Users/igorvasiljevic/opengv_devel/opengv/python/bin" _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;206;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_absolute_pose_sac "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_absolute_pose_sac")
set_tests_properties(test_absolute_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;212;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_absolute_pose "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_noncentral_absolute_pose")
set_tests_properties(test_noncentral_absolute_pose PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;218;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_absolute_pose_sac "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_noncentral_absolute_pose_sac")
set_tests_properties(test_noncentral_absolute_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;224;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_multi_noncentral_absolute_pose_sac "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_multi_noncentral_absolute_pose_sac")
set_tests_properties(test_multi_noncentral_absolute_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;230;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_relative_pose")
set_tests_properties(test_relative_pose PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;236;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose_rotationOnly "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_relative_pose_rotationOnly")
set_tests_properties(test_relative_pose_rotationOnly PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;242;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose_rotationOnly_sac "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_relative_pose_rotationOnly_sac")
set_tests_properties(test_relative_pose_rotationOnly_sac PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;248;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose_sac "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_relative_pose_sac")
set_tests_properties(test_relative_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;254;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_relative_pose "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_noncentral_relative_pose")
set_tests_properties(test_noncentral_relative_pose PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;260;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_relative_pose_sac "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_noncentral_relative_pose_sac")
set_tests_properties(test_noncentral_relative_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;266;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_multi_noncentral_relative_pose_sac "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_multi_noncentral_relative_pose_sac")
set_tests_properties(test_multi_noncentral_relative_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;272;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_eigensolver_sac "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_eigensolver_sac")
set_tests_properties(test_eigensolver_sac PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;278;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_triangulation "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_triangulation")
set_tests_properties(test_triangulation PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;284;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_eigensolver "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_eigensolver")
set_tests_properties(test_eigensolver PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;290;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_point_cloud "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_point_cloud")
set_tests_properties(test_point_cloud PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;296;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_point_cloud_sac "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_point_cloud_sac")
set_tests_properties(test_point_cloud_sac PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;302;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
add_test(test_Sturm "/Users/igorvasiljevic/opengv_devel/opengv/python/bin/test_Sturm")
set_tests_properties(test_Sturm PROPERTIES  _BACKTRACE_TRIPLES "/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;308;add_test;/Users/igorvasiljevic/opengv_devel/opengv/CMakeLists.txt;0;")
subdirs("python")
